@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 200
skinparam ArrowFontSize 10
skinparam ArrowColor #444444
skinparam ComponentFontSize 11
skinparam ComponentPadding 10
skinparam DefaultTextAlignment center
skinparam ArrowMessageAlignment center
LAYOUT_LEFT_RIGHT()

title C3 — Device Management Service (NestJS)

Container_Boundary(device_mgmt, "Device Management Service (NestJS)") {
    Component(device_module, "DeviceModule", "NestJS Module", "Конфигурация модулей и зависимостей.")
    Component(device_controller, "DeviceController", "NestJS Controller", "HTTP API для /devices.")
    Component(device_service, "DeviceService", "NestJS Service", "Логика регистрации и управления устройствами.")
    Component(device_repository, "DeviceRepository", "ORM Repo", "Работа с устройствами в БД.")
    Component(device_entity, "DeviceEntity", "Entity", "Модель устройства.")
    Component(device_events_publisher, "DeviceEventsPublisher", "Provider", "Публикует события device.*")
}

ContainerDb(device_db, "Device DB", "PostgreSQL", "Реестр устройств.")
System_Ext(message_broker, "Message Broker", "Kafka/RabbitMQ", "Обмен событиями.")
System_Ext(api_gateway, "API Gateway", "Edge", "Маршрутизация клиентов.")

Rel(api_gateway, device_controller, "HTTP /devices/*", "JSON")
Rel(device_controller, device_service, "Вызывает", "")
Rel(device_service, device_repository, "Чтение/запись", "ORM")
Rel(device_repository, device_db, "Чтение/запись", "SQL")
Rel(device_service, device_entity, "Работа с моделью", "")
Rel(device_service, device_events_publisher, "Публикация событий", "events")
Rel(device_events_publisher, message_broker, "publish device.*", "events")

@enduml
