version: '3.9'

services:
  postgres:
    build:
      context: ./          # контекст = папка apps
      dockerfile: ./postgres.Dockerfile
    container_name: smart_home_db
    environment:
      POSTGRES_DB: smart_home_db
      POSTGRES_USER: smart_home_user
      POSTGRES_PASSWORD: smart_home_pass
    ports:
      - "5432:5432"

  temperature-api:
    build:
      context: ./heating-service
      dockerfile: Dockerfile
    container_name: temperature_api
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
